### ISSUE TITLE
[Setting] Test Deploy

### ISSUE THREAD

**Issue by zbqmgldjfh** [soolsul/soolsul-server#58]
## 🙋🏻‍♂️ 환경 세팅
간단하게 중간 제출용으로 배포를 해본다.

- [ ] Docker 이용
- [x] EC2 1대 이용
- [x] RDS 이용

```yml
spring:
  datasource:
    url: jdbc:mysql://soolsul-database.cdgpshukrldy.ap-northeast-2.rds.amazonaws.com:3306/soolsul
    username: ${name}
    password: ${password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true # 추후 초기화 데이터 삽입용
  sql:
    init:
      mode: always
      data-locations: classpath:sql/data.sql
  profiles:
    include: aws

management:
  endpoint:
    web:
      exposure:
        include: health
    health:
      show-details: always


jwt:
  expire-length: 1800000 # 30min
  refresh-length: 86400000 # 1day
  access:
    private:
      MIIBVAIBADANBgkqhkiG9w0BAQEFAASCAT4wggE6AgEAAkEAuODLt1+2EB1mKHd1
      cqP5Cwc0eC4jnuznnS3TIBTdau7SHIqUJeC6Snmu5Eh15oBBfV/aD/8T81LKnjH8
      RwslCwIDAQABAkA/HoiOv7+h+teRA0/25uK1EC2qxl3k+Y8OC8IkFtuNkQwG+WNf
      7i05kquWNwTzwFNvwoIYujSfGy2OKhjUlMj5AiEA+OcUBx9yWMo9NIH6/bR/qBhH
      H7Q9jP5LvCoM5HaB1FcCIQC+JlsTg7I0DwxanNo6/J0mH1bhBBmzm++mvtaDkqSk
      bQIgLulenPkQVCvJ3VuiMq8SYFwzC4atEyXaoFxMkcLENYECIEx1P8no+o7UPjNx
      Po7ZZJcfot93tp3x5bs2oSrmnC1BAiEA4m9Gfv+KDazDYC4J5Sm0mEG8F40xWlCu
      Q9U+hUuK5Kw=
    public:
      MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBALjgy7dfthAdZih3dXKj+QsHNHguI57s
      550t0yAU3Wru0hyKlCXgukp5ruRIdeaAQX1f2g//E/NSyp4x/EcLJQsCAwEAAQ==
  refresh:
    private:
      MIIBVAIBADANBgkqhkiG9w0BAQEFAASCAT4wggE6AgEAAkEAhkZSIBQLI8HtQXOL
      ioAezKkqoqQTubAc4JdPsfToIzlFXMDPVTxyW34weBFuDnFm9ylPIc+XLknAeufX
      nho0+QIDAQABAkBfj9iO//TVpATo2gTrszc4TQUM710igFZs+QM9EaHMvrs/Z+CF
      vSGGuUt9m2yCl+gx0XZ0aPlYQahaP5g1VX+pAiEA7ytsmVYOYaeCEICSvszbfPUa
      TMeU17NKURauandnZB8CIQCPuT4rRi69J/oMiwjoxAw2HVxi3W63LMeOw9NH3g2D
      5wIgVvQvuJPsCJ8RD5TfRVVPm1+1XyLUv5NkupSHdxfQVDsCIBM+Y2OZ7xImsyVQ
      zG2WKmhogAFA0t014rZr4/NAeSDLAiEA0+SpdBmmaUvKOgptFuJ3d3Zphqrrc3Tc
      yEreggkRiG0=
    public:
      MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAIZGUiAUCyPB7UFzi4qAHsypKqKkE7mw
      HOCXT7H06CM5RVzAz1U8clt+MHgRbg5xZvcpTyHPly5JwHrn154aNPkCAwEAAQ==

```

## 📖 참고 사항
공유할 내용, 레퍼런스, 추가로 발생할 것으로 예상되는 이슈, 스크린샷 등을 넣어 주세요.
- 추가적으로 필요한 내용은 comment로 남겨주세요.
